### ISSUE TITLE
`Meta.view_name` not heeded in HyperlinkedModelSerializer

### ISSUE THREAD

**Issue by rknLA** [encode/django-rest-framework#5291]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

* Create a `HyperlinkedModelSerializer` subclass
* Add `view_name` to the `Meta` class of your subclass
* Attempt to serialize an instance of the model

## Expected behavior
* The model should serialize, and the `url` field of the model should use the correct view name.

## Actual behavior
* If the default view name is not defined, the model does not successfully serialize.  If it is defined, then the default `model-detail` URL will render, rather than the `view_name` view.

---
Some backstory here:

I was trying to solve the same problem as https://github.com/encode/django-rest-framework/issues/1321, except that IMO, inheriting a Meta class that defines a namespace is a better approach for my particular use case than manually setting all of the view names.

In this process, I discovered that even when I set the view name manually, my tests still fail with a:

```
django.core.exceptions.ImproperlyConfigured: Could not resolve URL for hyperlinked relationship using view name "model-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.
```

It looks like https://github.com/encode/django-rest-framework/issues/4854 was also closed for a similar reason, explaining that setting `view_name` **should** work, but when I look at the code path that actually gets the URL, it doesn't even check for `view_name` in the serializer ([build_url_field](https://github.com/encode/django-rest-framework/blob/master/rest_framework/serializers.py#L1253) calls [get_url_kwargs](https://github.com/encode/django-rest-framework/blob/master/rest_framework/utils/field_mapping.py#L292), which only looks at the model to get the default `view_name`)

**Comment by carltongibson** [comment]
#1321 was a **long time ago** but — `view_name` is **not** meant to function on the **serializer**. Rather it functions on the individual fields. 

You pass `view_name` to individual fields in the `extra_kwargs` dict, or you instantiate them explicitly and do the same. 

See [How hyperlinked views are determined](http://www.django-rest-framework.org/api-guide/serializers/#how-hyperlinked-views-are-determined) in the Serializers docs. 

Closing as _Expected Behaviour_.
