### ISSUE TITLE
Meta.extra_kwargs "validators" is ignored for a m2m field (at least for max length)

### ISSUE THREAD

**Issue by theoden-dd** [encode/django-rest-framework#5366]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. Create a model with an m2m field
1. Create a serializer for that model having `Meta.extra_kwargs = {'field': {'validators': [MaxLengthValidator(1)]} }`
1. Create instance of the model along with 2 values in the m2m field.
1. Serialize it.

Reproducer project: https://github.com/theoden-dd/django-reproducer/tree/extra_kwargs-validators-for-max-length

## Expected behavior

Validation should fail with too many values.

## Actual behavior

Everything seems to be fine.

**Comment by rpkilby** [comment]
Hi @theoden-dd. There are two separate misunderstanding here:

- `MaxLengthValidator` is intended to test the *length* of a value. eg, the length of a string of characters. It is not intended to test the count of items in a to-many relationship.
- [Validation](http://www.django-rest-framework.org/api-guide/serializers/#validation) occurs during deserialization, not serialization.
