### ISSUE TITLE
Read only fields in Meta class still validate the field

### ISSUE THREAD

**Issue by tirkarthi** [encode/django-rest-framework#5955]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

models.py

```
from django.db import models

class Todo(models.Model):
    title = models.CharField(max_length=50, null=True)
    description = models.CharField(max_length=200, null=True)
    status = models.BooleanField(default=False)
```

serializers.py 

```
from rest_framework import serializers
from .models import Todo

class TodoSerializer(serializers.ModelSerializer):

    status = serializers.BooleanField(required=False)

    class Meta:
        model = Todo
        fields = "__all__"
        read_only_fields = ('status', )
```

When I have 'status' in the `read_only_fields` in Meta class then validation of data is done and the data is also included in the initial data. 

```
 foo_django $ python manage.py shell
Python 3.5.2 (default, Oct 11 2016, 05:00:16)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from todo.serializers import *
>>> foo = TodoSerializer(data={'status': 'wer'})
>>> foo.is_valid()
False
>>> foo.errors
{'status': [ErrorDetail(string='"wer" is not a valid boolean.', code='invalid')]}
>>> foo.get_initial()
OrderedDict([('status', 'wer')])
>>>
```

Meanwhile if I have the read_only as True in the class definition it works fine ignoring the field in the initial_data.

serializers.py 

```
from rest_framework import serializers
from .models import Todo

class TodoSerializer(serializers.ModelSerializer):

    status = serializers.BooleanField(required=False, read_only=True)

    class Meta:
        model = Todo
        fields = "__all__"
```

```
foo_django python manage.py shell
Python 3.5.2 (default, Oct 11 2016, 05:00:16)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from todo.serializers import *
>>> foo = TodoSerializer(data={'status': 'wer'})
>>> foo.is_valid()
True
>>> foo.get_initial()
OrderedDict()
```

## Expected behavior

The field should not be listed in `get_initial` response and validated when I set it in `read_only_fields`

## Actual behavior

The field is listed in `get_initial` response and validated even when I set it in `read_only_fields`. I also need to add `read_only=True` again in the definition to get the desired output.

**Comment by tirkarthi** [comment]
Seems this related to https://github.com/encode/django-rest-framework/issues/3533 . Sorry, just changed some keywords in GitHub search to get to this issue. I am using `read_only=True` in addition to using it declaring it in Meta class as a workaround for now.

Feel free to close this if you feel it's a duplicate.

Thanks for the great library.
