### ISSUE TITLE
Provide a way to add a description field (mentioned as a TODO)

### ISSUE THREAD

**Issue by omnipresent07** [encode/django-rest-framework#7525]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

The `description` field in the master branch has a TODO that says "Put something meaningful in here". It would be ideal if the developers can add custom text in this field so that responses of the description can be concrete.
