### ISSUE TITLE
rest_framework.authtoken gives TypeError: 'class Meta' got invalid attribute(s): constraints

### ISSUE THREAD

**Issue by westhomas** [encode/django-rest-framework#7636]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Pips:
```
Django==3.1.3
djangorestframework==3.12.2
```

My settings.py for rest framework:
```python
INSTALLED_APPS = [
...
    'rest_framework',
    'rest_framework.authtoken',
...
]

REST_FRAMEWORK.update({
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAdminUser',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
})
```

## Expected behavior

No exceptions on migrate.

## Actual behavior

```
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, ...
Running migrations:
  Applying authtoken.0003_tokenproxy...Traceback (most recent call last):
...
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/migration.py", line 119, in apply
    operation.state_forwards(self.app_label, project_state)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/operations/models.py", line 91, in state_forwards
    list(self.managers),
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/state.py", line 105, in add_model
    self.reload_model(app_label, model_name)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/state.py", line 166, in reload_model
    self._reload(related_models)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/state.py", line 199, in _reload
    self.apps.render_multiple(states_to_be_rendered)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/state.py", line 323, in render_multiple
    model.render(self)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/state.py", line 626, in render
    body,
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 124, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 325, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/options.py", line 206, in contribute_to_class
    raise TypeError("'class Meta' got invalid attribute(s): %s" % ','.join(meta_attrs.keys()))
TypeError: 'class Meta' got invalid attribute(s): constraints
```

Cloned master and commented out this line:

https://github.com/encode/django-rest-framework/blob/master/rest_framework/authtoken/migrations/0003_tokenproxy.py#L21

Seems to work fine after that.

**Comment by westhomas** [comment]
Django versioning goof. Closing.
