### ISSUE TITLE
serializers- many-many fields are ignored when included in meta read_only_fields

### ISSUE THREAD

**Issue by CosmicReindeer** [encode/django-rest-framework#7677]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
- make a model serializer, which has atleast one many to many field.
- add the many to many field to the read_only_fields list in class meta of the serializer.
- an example:
```py
class ClusterSerializer(serializers.ModelSerializer):
    """
    A serialized DataSheetsCluster Object.
    Clusters have their own:
        - array of members
        - array of roles
        - array of categories
        - array of datasheets
    """

    class Meta:
        model = DataSheetsCluster
        read_only_fields = ['size_limit', 'members', 'roles', 'datasheets']
        exclude = ['categories']

    @property
    def cluster_size(self):
        return field_data_manager.get_cluster_size(self.data['id'])

    size = serializers.ReadOnlyField(source='cluster_size')
    members = partial.PartialMemberSerializer(many=True)
    roles = partial.PartialRoleSerializer(many=True)
    datasheets = partial.PartialDataSheetSerializer(many=True)
```
here, `members`, `roles` and `datasheets` are many-many fields.
## Expected behavior
- the many to many field must be marked as not required.
- the serializer must not raise any required- error regarding the same.
## Actual behavior
-  the serializer ignores the many-many fields included.
- it raises api errors that the many-many- field must be passed in by the client.

**Comment by kevin-brown** [comment]
I believe `read_only_fields` (and by extension, `extra_kwargs` since that is what is autofilled by `read_only_fields`) is ignored if the field is explicitly declared on the serializer. The helper only works for fields which are automatically generated based on the model, since for those you aren't explicitly stating what field/options you want to use.

This is briefly mentioned in the docs under [Additional keyword arguments](https://www.django-rest-framework.org/api-guide/serializers/#additional-keyword-arguments):

> Please keep in mind that, if the field has already been explicitly declared on the serializer class, then the `extra_kwargs` option will be ignored.

You can tell DRF to treat the declared field as read-only by [specifying `read_only=True` in the constructor](https://www.django-rest-framework.org/api-guide/fields/#read_only).

----

It may be beneficial to surface errors in cases where a field is both explicitly declared and present in `extra_kwargs` or `read_only_fields`. I'm not sure how difficult that would be to detect.

**Comment by CosmicReindeer** [comment]
thanks! I get it now, but I think it would be more convienient if we could just include nested serializer fields in the `read_only_fields` list itself.

I don't want to explicitly define it in the constructor always.
